// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlKrNvauJmhvfJE9fI8eI1vr4LP-w2lKI',
    appId: '1:592395231921:web:ea9c6ea74d5ce63953b890',
    messagingSenderId: '592395231921',
    projectId: 'mamatomo-f7f94',
    authDomain: 'mamatomo-f7f94.firebaseapp.com',
    databaseURL: 'https://mamatomo-f7f94-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mamatomo-f7f94.appspot.com',
    measurementId: 'G-92L5Z2PKB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk4IQ-55fTlU3nOiCT5jRiAlUzmZS3-s4',
    appId: '1:592395231921:android:066dcf568ca55fd353b890',
    messagingSenderId: '592395231921',
    projectId: 'mamatomo-f7f94',
    databaseURL: 'https://mamatomo-f7f94-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mamatomo-f7f94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSmD2N7Dy5XAWfQSDX6wh5-y7FXWNR1S4',
    appId: '1:592395231921:ios:1e6e4688f9977e0453b890',
    messagingSenderId: '592395231921',
    projectId: 'mamatomo-f7f94',
    databaseURL: 'https://mamatomo-f7f94-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mamatomo-f7f94.appspot.com',
    iosBundleId: 'com.example.mamatomo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSmD2N7Dy5XAWfQSDX6wh5-y7FXWNR1S4',
    appId: '1:592395231921:ios:c1d476e6561a35d953b890',
    messagingSenderId: '592395231921',
    projectId: 'mamatomo-f7f94',
    databaseURL: 'https://mamatomo-f7f94-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mamatomo-f7f94.appspot.com',
    iosBundleId: 'com.example.mamatomo.RunnerTests',
  );
}
